CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCT_ID BIGINT NOT NULL,
    ACCT_ACTIVE_STATUS CHAR(1),
    ACCT_CURR_BAL DECIMAL(12, 2),
    ACCT_CREDIT_LIMIT DECIMAL(12, 2),
    ACCT_CASH_CREDIT_LIMIT DECIMAL(12, 2),
    ACCT_OPEN_DATE DATE,
    ACCT_EXPIRATION_DATE DATE,
    ACCT_REISSUE_DATE DATE,
    ACCT_CURR_CYC_CREDIT DECIMAL(12, 2),
    ACCT_CURR_CYC_DEBIT DECIMAL(12, 2),
    ACCT_ADDR_ZIP CHAR(10),
    ACCT_GROUP_ID CHAR(10),
    PRIMARY KEY (ACCT_ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
    TRAN_ID CHAR(16) NOT NULL,
    TRAN_TYPE_CD CHAR(2),
    TRAN_CAT_CD INTEGER,
    TRAN_SOURCE CHAR(10),
    TRAN_DESC CHAR(100),
    TRAN_AMT DECIMAL(11, 2),
    TRAN_MERCHANT_ID INTEGER,
    TRAN_MERCHANT_NAME CHAR(50),
    TRAN_MERCHANT_CITY CHAR(50),
    TRAN_MERCHANT_ZIP CHAR(10),
    TRAN_CARD_NUM CHAR(16),
    TRAN_ORIG_TS CHAR(26),
    TRAN_PROC_TS CHAR(26),
    PRIMARY KEY (TRAN_ID)
);

CREATE TABLE IF NOT EXISTS CARD_XREF (
    XREF_CARD_NUM CHAR(16) NOT NULL,
    XREF_CUST_ID INTEGER,
    XREF_ACCT_ID BIGINT,
    PRIMARY KEY (XREF_CARD_NUM)
);

CREATE TABLE IF NOT EXISTS DISCLOSURE_GROUP (
    DIS_ACCT_GROUP_ID CHAR(10) NOT NULL,
    DIS_TRAN_TYPE_CD CHAR(2) NOT NULL,
    DIS_TRAN_CAT_CD INTEGER NOT NULL,
    DIS_INT_RATE DECIMAL(6, 2),
    PRIMARY KEY (DIS_ACCT_GROUP_ID, DIS_TRAN_TYPE_CD, DIS_TRAN_CAT_CD)
);

CREATE TABLE IF NOT EXISTS TRAN_CAT_BAL (
    TRANCAT_ACCT_ID BIGINT NOT NULL,
    TRANCAT_TYPE_CD CHAR(2) NOT NULL,
    TRANCAT_CD INTEGER NOT NULL,
    TRAN_CAT_BAL DECIMAL(11, 2),
    PRIMARY KEY (TRANCAT_ACCT_ID, TRANCAT_TYPE_CD, TRANCAT_CD)
);
