CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCT_ID BIGINT NOT NULL,
    ACCT_ACTIVE_STATUS CHAR(1),
    ACCT_CURR_BAL DECIMAL(12, 2),
    ACCT_CREDIT_LIMIT DECIMAL(12, 2),
    ACCT_CASH_CREDIT_LIMIT DECIMAL(12, 2),
    ACCT_OPEN_DATE DATE,
    ACCT_EXPIRATION_DATE DATE,
    ACCT_REISSUE_DATE DATE,
    ACCT_CURR_CYC_CREDIT DECIMAL(12, 2),
    ACCT_CURR_CYC_DEBIT DECIMAL(12, 2),
    ACCT_ADDR_ZIP CHAR(10),
    ACCT_GROUP_ID CHAR(10),
    PRIMARY KEY (ACCT_ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
    TRAN_ID CHAR(16) NOT NULL,
    TRAN_TYPE_CD CHAR(2),
    TRAN_CAT_CD INTEGER,
    TRAN_SOURCE CHAR(10),
    TRAN_DESC CHAR(100),
    TRAN_AMT DECIMAL(11, 2),
    TRAN_MERCHANT_ID INTEGER,
    TRAN_MERCHANT_NAME CHAR(50),
    TRAN_MERCHANT_CITY CHAR(50),
    TRAN_MERCHANT_ZIP CHAR(10),
    TRAN_CARD_NUM CHAR(16),
    TRAN_ORIG_TS CHAR(26),
    TRAN_PROC_TS CHAR(26),
    PRIMARY KEY (TRAN_ID)
);

CREATE TABLE IF NOT EXISTS CARD_XREF (
    XREF_CARD_NUM CHAR(16) NOT NULL,
    XREF_CUST_ID INTEGER,
    XREF_ACCT_ID BIGINT,
    PRIMARY KEY (XREF_CARD_NUM)
);

CREATE TABLE IF NOT EXISTS DISCLOSURE_GROUP (
    DIS_ACCT_GROUP_ID CHAR(10) NOT NULL,
    DIS_TRAN_TYPE_CD CHAR(2) NOT NULL,
    DIS_TRAN_CAT_CD INTEGER NOT NULL,
    DIS_INT_RATE DECIMAL(6, 2),
    PRIMARY KEY (DIS_ACCT_GROUP_ID, DIS_TRAN_TYPE_CD, DIS_TRAN_CAT_CD)
);

CREATE TABLE IF NOT EXISTS TRAN_CAT_BAL (
    TRANCAT_ACCT_ID BIGINT NOT NULL,
    TRANCAT_TYPE_CD CHAR(2) NOT NULL,
    TRANCAT_CD INTEGER NOT NULL,
    TRAN_CAT_BAL DECIMAL(11, 2),
    PRIMARY KEY (TRANCAT_ACCT_ID, TRANCAT_TYPE_CD, TRANCAT_CD)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUST_ID INTEGER NOT NULL,
    CUST_FIRST_NAME VARCHAR(25),
    CUST_MIDDLE_NAME VARCHAR(25),
    CUST_LAST_NAME VARCHAR(25),
    CUST_ADDR_LINE_1 VARCHAR(50),
    CUST_ADDR_LINE_2 VARCHAR(50),
    CUST_ADDR_LINE_3 VARCHAR(50),
    CUST_ADDR_STATE_CD VARCHAR(2),
    CUST_ADDR_COUNTRY_CD VARCHAR(3),
    CUST_ADDR_ZIP VARCHAR(10),
    CUST_PHONE_NUM_1 VARCHAR(15),
    CUST_PHONE_NUM_2 VARCHAR(15),
    CUST_SSN INTEGER,
    CUST_GOVT_ISSUED_ID VARCHAR(20),
    CUST_DOB_YYYY_MM_DD DATE,
    CUST_EFT_ACCOUNT_ID VARCHAR(10),
    CUST_PRI_CARD_HOLDER_IND VARCHAR(1),
    CUST_FICO_CREDIT_SCORE INTEGER,
    PRIMARY KEY (CUST_ID)
);

CREATE TABLE IF NOT EXISTS USRSEC (
    SEC_USR_ID VARCHAR(8) NOT NULL,
    SEC_USR_FNAME VARCHAR(20),
    SEC_USR_LNAME VARCHAR(20),
    SEC_USR_PWD VARCHAR(8),
    SEC_USR_TYPE VARCHAR(1),
    SEC_USR_FILLER VARCHAR(23),
    PRIMARY KEY (SEC_USR_ID)
);

CREATE TABLE IF NOT EXISTS CARD (
    CARD_NUM VARCHAR(16) NOT NULL,
    CARD_ACCT_ID BIGINT NOT NULL,
    CARD_CVV_CD INTEGER,
    CARD_EMBOSSED_NAME VARCHAR(50),
    CARD_EXPIRAION_DATE VARCHAR(10),
    CARD_ACTIVE_STATUS VARCHAR(1),
    PRIMARY KEY (CARD_NUM)
);

CREATE TABLE IF NOT EXISTS DAILY_TRANSACTION (
    DALYTRAN_ID VARCHAR(16) NOT NULL,
    DALYTRAN_TYPE_CD VARCHAR(2),
    DALYTRAN_CAT_CD INTEGER,
    DALYTRAN_SOURCE VARCHAR(10),
    DALYTRAN_DESC VARCHAR(100),
    DALYTRAN_AMT DECIMAL(11, 2),
    DALYTRAN_MERCHANT_ID INTEGER,
    DALYTRAN_MERCHANT_NAME VARCHAR(50),
    DALYTRAN_MERCHANT_CITY VARCHAR(50),
    DALYTRAN_MERCHANT_ZIP VARCHAR(10),
    DALYTRAN_CARD_NUM VARCHAR(16),
    DALYTRAN_ORIG_TS VARCHAR(26),
    DALYTRAN_PROC_TS VARCHAR(26),
    DALYTRAN_STATUS VARCHAR(20),
    DALYTRAN_REJECT_REASON VARCHAR(100),
    PRIMARY KEY (DALYTRAN_ID)
);
